# Generated by Django 4.2.13 on 2024-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('IMEI', models.CharField(max_length=100)),
                ('body_style', models.CharField(choices=[('sedan', 'Sedan'), ('coupe', 'Coupe'), ('sports cart', 'Sports car'), ('station wagon', 'Station wagon'), ('hatchback', 'hatchback'), ('convertible', 'Convertible'), ('suv', 'Suv'), ('minivan', 'Minivan'), ('pickup truck', 'Pickup truck')], default='sedan', max_length=50)),
                ('license', models.CharField(choices=[('provided', 'Provided'), ('not provided', 'Not Provided')], default='provided', max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('leased', 'Leased'), ('repair', 'In Repair')], default='ready', max_length=50)),
            ],
        ),
    ]
